[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/gophercloud/gophercloud"

[[constraint]]
  branch = "master"
  name = "github.com/xlab/treeprint"
